// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "omilos.proto" (package "omilos_grpc", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Omilos } from "./omilos";
import type { Casts } from "./omilos";
import type { GetCastsRequest } from "./omilos";
import type { Cast } from "./omilos";
import type { GetCastRequest } from "./omilos";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { User } from "./omilos";
import type { GetUserRequest } from "./omilos";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service omilos_grpc.Omilos
 */
export interface IOmilosClient {
    /**
     * @generated from protobuf rpc: GetUser(omilos_grpc.GetUserRequest) returns (omilos_grpc.User);
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, User>;
    /**
     * @generated from protobuf rpc: GetCast(omilos_grpc.GetCastRequest) returns (omilos_grpc.Cast);
     */
    getCast(input: GetCastRequest, options?: RpcOptions): UnaryCall<GetCastRequest, Cast>;
    /**
     * @generated from protobuf rpc: GetCasts(omilos_grpc.GetCastsRequest) returns (omilos_grpc.Casts);
     */
    getCasts(input: GetCastsRequest, options?: RpcOptions): UnaryCall<GetCastsRequest, Casts>;
}
/**
 * @generated from protobuf service omilos_grpc.Omilos
 */
export class OmilosClient implements IOmilosClient, ServiceInfo {
    typeName = Omilos.typeName;
    methods = Omilos.methods;
    options = Omilos.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetUser(omilos_grpc.GetUserRequest) returns (omilos_grpc.User);
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, User> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCast(omilos_grpc.GetCastRequest) returns (omilos_grpc.Cast);
     */
    getCast(input: GetCastRequest, options?: RpcOptions): UnaryCall<GetCastRequest, Cast> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCastRequest, Cast>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCasts(omilos_grpc.GetCastsRequest) returns (omilos_grpc.Casts);
     */
    getCasts(input: GetCastsRequest, options?: RpcOptions): UnaryCall<GetCastsRequest, Casts> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCastsRequest, Casts>("unary", this._transport, method, opt, input);
    }
}
