// source: omilos.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.omilos_grpc.Author', null, global);
goog.exportSymbol('proto.omilos_grpc.Cast', null, global);
goog.exportSymbol('proto.omilos_grpc.CastsRequest', null, global);
goog.exportSymbol('proto.omilos_grpc.CastsResponse', null, global);
goog.exportSymbol('proto.omilos_grpc.ProfilePicture', null, global);
goog.exportSymbol('proto.omilos_grpc.ViewContext', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.omilos_grpc.CastsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.omilos_grpc.CastsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.omilos_grpc.CastsRequest.displayName = 'proto.omilos_grpc.CastsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.omilos_grpc.CastsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.omilos_grpc.CastsResponse.repeatedFields_, null);
};
goog.inherits(proto.omilos_grpc.CastsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.omilos_grpc.CastsResponse.displayName = 'proto.omilos_grpc.CastsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.omilos_grpc.Cast = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.omilos_grpc.Cast, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.omilos_grpc.Cast.displayName = 'proto.omilos_grpc.Cast';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.omilos_grpc.ViewContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.omilos_grpc.ViewContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.omilos_grpc.ViewContext.displayName = 'proto.omilos_grpc.ViewContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.omilos_grpc.Author = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.omilos_grpc.Author, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.omilos_grpc.Author.displayName = 'proto.omilos_grpc.Author';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.omilos_grpc.ProfilePicture = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.omilos_grpc.ProfilePicture, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.omilos_grpc.ProfilePicture.displayName = 'proto.omilos_grpc.ProfilePicture';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.omilos_grpc.CastsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.omilos_grpc.CastsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.omilos_grpc.CastsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.CastsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fid: (f = msg.getFid()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.omilos_grpc.CastsRequest}
 */
proto.omilos_grpc.CastsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.omilos_grpc.CastsRequest;
  return proto.omilos_grpc.CastsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.omilos_grpc.CastsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.omilos_grpc.CastsRequest}
 */
proto.omilos_grpc.CastsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setFid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.omilos_grpc.CastsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.omilos_grpc.CastsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.omilos_grpc.CastsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.CastsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue fid = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.omilos_grpc.CastsRequest.prototype.getFid = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.omilos_grpc.CastsRequest} returns this
*/
proto.omilos_grpc.CastsRequest.prototype.setFid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.omilos_grpc.CastsRequest} returns this
 */
proto.omilos_grpc.CastsRequest.prototype.clearFid = function() {
  return this.setFid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.omilos_grpc.CastsRequest.prototype.hasFid = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.omilos_grpc.CastsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.omilos_grpc.CastsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.omilos_grpc.CastsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.omilos_grpc.CastsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.CastsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    castsList: jspb.Message.toObjectList(msg.getCastsList(),
    proto.omilos_grpc.Cast.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.omilos_grpc.CastsResponse}
 */
proto.omilos_grpc.CastsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.omilos_grpc.CastsResponse;
  return proto.omilos_grpc.CastsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.omilos_grpc.CastsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.omilos_grpc.CastsResponse}
 */
proto.omilos_grpc.CastsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.omilos_grpc.Cast;
      reader.readMessage(value,proto.omilos_grpc.Cast.deserializeBinaryFromReader);
      msg.addCasts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.omilos_grpc.CastsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.omilos_grpc.CastsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.omilos_grpc.CastsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.CastsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCastsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.omilos_grpc.Cast.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Cast casts = 1;
 * @return {!Array<!proto.omilos_grpc.Cast>}
 */
proto.omilos_grpc.CastsResponse.prototype.getCastsList = function() {
  return /** @type{!Array<!proto.omilos_grpc.Cast>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.omilos_grpc.Cast, 1));
};


/**
 * @param {!Array<!proto.omilos_grpc.Cast>} value
 * @return {!proto.omilos_grpc.CastsResponse} returns this
*/
proto.omilos_grpc.CastsResponse.prototype.setCastsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.omilos_grpc.Cast=} opt_value
 * @param {number=} opt_index
 * @return {!proto.omilos_grpc.Cast}
 */
proto.omilos_grpc.CastsResponse.prototype.addCasts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.omilos_grpc.Cast, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.omilos_grpc.CastsResponse} returns this
 */
proto.omilos_grpc.CastsResponse.prototype.clearCastsList = function() {
  return this.setCastsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.omilos_grpc.Cast.prototype.toObject = function(opt_includeInstance) {
  return proto.omilos_grpc.Cast.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.omilos_grpc.Cast} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.Cast.toObject = function(includeInstance, msg) {
  var f, obj = {
    hash: jspb.Message.getFieldWithDefault(msg, 1, ""),
    threadHash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    text: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
    replies: jspb.Message.getFieldWithDefault(msg, 5, 0),
    reactions: jspb.Message.getFieldWithDefault(msg, 6, 0),
    recasts: jspb.Message.getFieldWithDefault(msg, 7, 0),
    watches: jspb.Message.getFieldWithDefault(msg, 8, 0),
    recast: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    viewContext: (f = msg.getViewContext()) && proto.omilos_grpc.ViewContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.omilos_grpc.Cast}
 */
proto.omilos_grpc.Cast.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.omilos_grpc.Cast;
  return proto.omilos_grpc.Cast.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.omilos_grpc.Cast} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.omilos_grpc.Cast}
 */
proto.omilos_grpc.Cast.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setThreadHash(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setReplies(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setReactions(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRecasts(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setWatches(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecast(value);
      break;
    case 10:
      var value = new proto.omilos_grpc.ViewContext;
      reader.readMessage(value,proto.omilos_grpc.ViewContext.deserializeBinaryFromReader);
      msg.setViewContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.omilos_grpc.Cast.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.omilos_grpc.Cast.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.omilos_grpc.Cast} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.Cast.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHash();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getThreadHash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getReplies();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getReactions();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getRecasts();
  if (f !== 0) {
    writer.writeUint64(
      7,
      f
    );
  }
  f = message.getWatches();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getRecast();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getViewContext();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.omilos_grpc.ViewContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string hash = 1;
 * @return {string}
 */
proto.omilos_grpc.Cast.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setHash = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string thread_hash = 2;
 * @return {string}
 */
proto.omilos_grpc.Cast.prototype.getThreadHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setThreadHash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string text = 3;
 * @return {string}
 */
proto.omilos_grpc.Cast.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 timestamp = 4;
 * @return {number}
 */
proto.omilos_grpc.Cast.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 replies = 5;
 * @return {number}
 */
proto.omilos_grpc.Cast.prototype.getReplies = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setReplies = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 reactions = 6;
 * @return {number}
 */
proto.omilos_grpc.Cast.prototype.getReactions = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setReactions = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint64 recasts = 7;
 * @return {number}
 */
proto.omilos_grpc.Cast.prototype.getRecasts = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setRecasts = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint64 watches = 8;
 * @return {number}
 */
proto.omilos_grpc.Cast.prototype.getWatches = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setWatches = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool recast = 9;
 * @return {boolean}
 */
proto.omilos_grpc.Cast.prototype.getRecast = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.setRecast = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional ViewContext view_context = 10;
 * @return {?proto.omilos_grpc.ViewContext}
 */
proto.omilos_grpc.Cast.prototype.getViewContext = function() {
  return /** @type{?proto.omilos_grpc.ViewContext} */ (
    jspb.Message.getWrapperField(this, proto.omilos_grpc.ViewContext, 10));
};


/**
 * @param {?proto.omilos_grpc.ViewContext|undefined} value
 * @return {!proto.omilos_grpc.Cast} returns this
*/
proto.omilos_grpc.Cast.prototype.setViewContext = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.omilos_grpc.Cast} returns this
 */
proto.omilos_grpc.Cast.prototype.clearViewContext = function() {
  return this.setViewContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.omilos_grpc.Cast.prototype.hasViewContext = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.omilos_grpc.ViewContext.prototype.toObject = function(opt_includeInstance) {
  return proto.omilos_grpc.ViewContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.omilos_grpc.ViewContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.ViewContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    reacted: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    recasted: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    watched: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.omilos_grpc.ViewContext}
 */
proto.omilos_grpc.ViewContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.omilos_grpc.ViewContext;
  return proto.omilos_grpc.ViewContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.omilos_grpc.ViewContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.omilos_grpc.ViewContext}
 */
proto.omilos_grpc.ViewContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setReacted(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRecasted(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setWatched(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.omilos_grpc.ViewContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.omilos_grpc.ViewContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.omilos_grpc.ViewContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.ViewContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReacted();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getRecasted();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getWatched();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional bool reacted = 1;
 * @return {boolean}
 */
proto.omilos_grpc.ViewContext.prototype.getReacted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.omilos_grpc.ViewContext} returns this
 */
proto.omilos_grpc.ViewContext.prototype.setReacted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool recasted = 2;
 * @return {boolean}
 */
proto.omilos_grpc.ViewContext.prototype.getRecasted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.omilos_grpc.ViewContext} returns this
 */
proto.omilos_grpc.ViewContext.prototype.setRecasted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool watched = 3;
 * @return {boolean}
 */
proto.omilos_grpc.ViewContext.prototype.getWatched = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.omilos_grpc.ViewContext} returns this
 */
proto.omilos_grpc.ViewContext.prototype.setWatched = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.omilos_grpc.Author.prototype.toObject = function(opt_includeInstance) {
  return proto.omilos_grpc.Author.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.omilos_grpc.Author} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.Author.toObject = function(includeInstance, msg) {
  var f, obj = {
    fid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    username: jspb.Message.getFieldWithDefault(msg, 2, ""),
    displayName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pfp: (f = msg.getPfp()) && proto.omilos_grpc.ProfilePicture.toObject(includeInstance, f),
    followerCount: jspb.Message.getFieldWithDefault(msg, 5, 0),
    followingCount: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.omilos_grpc.Author}
 */
proto.omilos_grpc.Author.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.omilos_grpc.Author;
  return proto.omilos_grpc.Author.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.omilos_grpc.Author} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.omilos_grpc.Author}
 */
proto.omilos_grpc.Author.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 4:
      var value = new proto.omilos_grpc.ProfilePicture;
      reader.readMessage(value,proto.omilos_grpc.ProfilePicture.deserializeBinaryFromReader);
      msg.setPfp(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFollowerCount(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFollowingCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.omilos_grpc.Author.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.omilos_grpc.Author.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.omilos_grpc.Author} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.Author.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFid();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPfp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.omilos_grpc.ProfilePicture.serializeBinaryToWriter
    );
  }
  f = message.getFollowerCount();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getFollowingCount();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
};


/**
 * optional uint64 fid = 1;
 * @return {number}
 */
proto.omilos_grpc.Author.prototype.getFid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Author} returns this
 */
proto.omilos_grpc.Author.prototype.setFid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string username = 2;
 * @return {string}
 */
proto.omilos_grpc.Author.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.omilos_grpc.Author} returns this
 */
proto.omilos_grpc.Author.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string display_name = 3;
 * @return {string}
 */
proto.omilos_grpc.Author.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.omilos_grpc.Author} returns this
 */
proto.omilos_grpc.Author.prototype.setDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional ProfilePicture pfp = 4;
 * @return {?proto.omilos_grpc.ProfilePicture}
 */
proto.omilos_grpc.Author.prototype.getPfp = function() {
  return /** @type{?proto.omilos_grpc.ProfilePicture} */ (
    jspb.Message.getWrapperField(this, proto.omilos_grpc.ProfilePicture, 4));
};


/**
 * @param {?proto.omilos_grpc.ProfilePicture|undefined} value
 * @return {!proto.omilos_grpc.Author} returns this
*/
proto.omilos_grpc.Author.prototype.setPfp = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.omilos_grpc.Author} returns this
 */
proto.omilos_grpc.Author.prototype.clearPfp = function() {
  return this.setPfp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.omilos_grpc.Author.prototype.hasPfp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint64 follower_count = 5;
 * @return {number}
 */
proto.omilos_grpc.Author.prototype.getFollowerCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Author} returns this
 */
proto.omilos_grpc.Author.prototype.setFollowerCount = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 following_count = 6;
 * @return {number}
 */
proto.omilos_grpc.Author.prototype.getFollowingCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.omilos_grpc.Author} returns this
 */
proto.omilos_grpc.Author.prototype.setFollowingCount = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.omilos_grpc.ProfilePicture.prototype.toObject = function(opt_includeInstance) {
  return proto.omilos_grpc.ProfilePicture.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.omilos_grpc.ProfilePicture} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.ProfilePicture.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    verified: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.omilos_grpc.ProfilePicture}
 */
proto.omilos_grpc.ProfilePicture.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.omilos_grpc.ProfilePicture;
  return proto.omilos_grpc.ProfilePicture.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.omilos_grpc.ProfilePicture} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.omilos_grpc.ProfilePicture}
 */
proto.omilos_grpc.ProfilePicture.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setVerified(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.omilos_grpc.ProfilePicture.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.omilos_grpc.ProfilePicture.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.omilos_grpc.ProfilePicture} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.omilos_grpc.ProfilePicture.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getVerified();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.omilos_grpc.ProfilePicture.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.omilos_grpc.ProfilePicture} returns this
 */
proto.omilos_grpc.ProfilePicture.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool verified = 2;
 * @return {boolean}
 */
proto.omilos_grpc.ProfilePicture.prototype.getVerified = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.omilos_grpc.ProfilePicture} returns this
 */
proto.omilos_grpc.ProfilePicture.prototype.setVerified = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


goog.object.extend(exports, proto.omilos_grpc);
