// User wants to fetch certificates, and credits

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.20.1
// source: omilos.proto

package omilos_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CastsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
}

func (x *CastsRequest) Reset() {
	*x = CastsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omilos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastsRequest) ProtoMessage() {}

func (x *CastsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omilos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastsRequest.ProtoReflect.Descriptor instead.
func (*CastsRequest) Descriptor() ([]byte, []int) {
	return file_omilos_proto_rawDescGZIP(), []int{0}
}

func (x *CastsRequest) GetFid() *wrapperspb.StringValue {
	if x != nil {
		return x.Fid
	}
	return nil
}

type CastsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Casts []*Cast `protobuf:"bytes,1,rep,name=casts,proto3" json:"casts,omitempty"`
}

func (x *CastsResponse) Reset() {
	*x = CastsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omilos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastsResponse) ProtoMessage() {}

func (x *CastsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omilos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastsResponse.ProtoReflect.Descriptor instead.
func (*CastsResponse) Descriptor() ([]byte, []int) {
	return file_omilos_proto_rawDescGZIP(), []int{1}
}

func (x *CastsResponse) GetCasts() []*Cast {
	if x != nil {
		return x.Casts
	}
	return nil
}

type Cast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash        string       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ThreadHash  string       `protobuf:"bytes,2,opt,name=thread_hash,json=threadHash,proto3" json:"thread_hash,omitempty"`
	Text        string       `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp   uint64       `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Replies     uint64       `protobuf:"varint,5,opt,name=replies,proto3" json:"replies,omitempty"`
	Reactions   uint64       `protobuf:"varint,6,opt,name=reactions,proto3" json:"reactions,omitempty"`
	Recasts     uint64       `protobuf:"varint,7,opt,name=recasts,proto3" json:"recasts,omitempty"` // TODO
	Watches     uint64       `protobuf:"varint,8,opt,name=watches,proto3" json:"watches,omitempty"`
	Recast      bool         `protobuf:"varint,9,opt,name=recast,proto3" json:"recast,omitempty"`
	ViewContext *ViewContext `protobuf:"bytes,10,opt,name=view_context,json=viewContext,proto3" json:"view_context,omitempty"`
}

func (x *Cast) Reset() {
	*x = Cast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omilos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_omilos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_omilos_proto_rawDescGZIP(), []int{2}
}

func (x *Cast) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Cast) GetThreadHash() string {
	if x != nil {
		return x.ThreadHash
	}
	return ""
}

func (x *Cast) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Cast) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Cast) GetReplies() uint64 {
	if x != nil {
		return x.Replies
	}
	return 0
}

func (x *Cast) GetReactions() uint64 {
	if x != nil {
		return x.Reactions
	}
	return 0
}

func (x *Cast) GetRecasts() uint64 {
	if x != nil {
		return x.Recasts
	}
	return 0
}

func (x *Cast) GetWatches() uint64 {
	if x != nil {
		return x.Watches
	}
	return 0
}

func (x *Cast) GetRecast() bool {
	if x != nil {
		return x.Recast
	}
	return false
}

func (x *Cast) GetViewContext() *ViewContext {
	if x != nil {
		return x.ViewContext
	}
	return nil
}

type ViewContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reacted  bool `protobuf:"varint,1,opt,name=reacted,proto3" json:"reacted,omitempty"`
	Recasted bool `protobuf:"varint,2,opt,name=recasted,proto3" json:"recasted,omitempty"`
	Watched  bool `protobuf:"varint,3,opt,name=watched,proto3" json:"watched,omitempty"`
}

func (x *ViewContext) Reset() {
	*x = ViewContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omilos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewContext) ProtoMessage() {}

func (x *ViewContext) ProtoReflect() protoreflect.Message {
	mi := &file_omilos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewContext.ProtoReflect.Descriptor instead.
func (*ViewContext) Descriptor() ([]byte, []int) {
	return file_omilos_proto_rawDescGZIP(), []int{3}
}

func (x *ViewContext) GetReacted() bool {
	if x != nil {
		return x.Reacted
	}
	return false
}

func (x *ViewContext) GetRecasted() bool {
	if x != nil {
		return x.Recasted
	}
	return false
}

func (x *ViewContext) GetWatched() bool {
	if x != nil {
		return x.Watched
	}
	return false
}

type Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fid            uint64          `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Username       string          `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName    string          `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Pfp            *ProfilePicture `protobuf:"bytes,4,opt,name=pfp,proto3" json:"pfp,omitempty"`
	FollowerCount  uint64          `protobuf:"varint,5,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FollowingCount uint64          `protobuf:"varint,6,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
}

func (x *Author) Reset() {
	*x = Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omilos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_omilos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_omilos_proto_rawDescGZIP(), []int{4}
}

func (x *Author) GetFid() uint64 {
	if x != nil {
		return x.Fid
	}
	return 0
}

func (x *Author) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Author) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Author) GetPfp() *ProfilePicture {
	if x != nil {
		return x.Pfp
	}
	return nil
}

func (x *Author) GetFollowerCount() uint64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *Author) GetFollowingCount() uint64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

type ProfilePicture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Verified bool   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *ProfilePicture) Reset() {
	*x = ProfilePicture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_omilos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfilePicture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilePicture) ProtoMessage() {}

func (x *ProfilePicture) ProtoReflect() protoreflect.Message {
	mi := &file_omilos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilePicture.ProtoReflect.Descriptor instead.
func (*ProfilePicture) Descriptor() ([]byte, []int) {
	return file_omilos_proto_rawDescGZIP(), []int{5}
}

func (x *ProfilePicture) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProfilePicture) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_omilos_proto protoreflect.FileDescriptor

var file_omilos_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x6f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0c, 0x43,
	0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x03, 0x66,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x66, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x0d, 0x43,
	0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05,
	0x63, 0x61, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x6d,
	0x69, 0x6c, 0x6f, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x52, 0x05,
	0x63, 0x61, 0x73, 0x74, 0x73, 0x22, 0xae, 0x02, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0c, 0x76, 0x69, 0x65,
	0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x69,
	0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0b, 0x76, 0x69, 0x65, 0x77, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x5d, 0x0a, 0x0b, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x63, 0x61, 0x73, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x77,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x64, 0x22, 0xd8, 0x01, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2d, 0x0a, 0x03, 0x70, 0x66, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x70, 0x66, 0x70,
	0x12, 0x25, 0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x3e, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x32, 0x4c, 0x0a, 0x06, 0x4f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x12, 0x42, 0x0a, 0x05, 0x43, 0x61,
	0x73, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x6f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x6f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x1f,
	0x5a, 0x1d, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6d, 0x69,
	0x6c, 0x6f, 0x73, 0x2f, 0x6f, 0x6d, 0x69, 0x6c, 0x6f, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_omilos_proto_rawDescOnce sync.Once
	file_omilos_proto_rawDescData = file_omilos_proto_rawDesc
)

func file_omilos_proto_rawDescGZIP() []byte {
	file_omilos_proto_rawDescOnce.Do(func() {
		file_omilos_proto_rawDescData = protoimpl.X.CompressGZIP(file_omilos_proto_rawDescData)
	})
	return file_omilos_proto_rawDescData
}

var file_omilos_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_omilos_proto_goTypes = []interface{}{
	(*CastsRequest)(nil),           // 0: omilos_grpc.CastsRequest
	(*CastsResponse)(nil),          // 1: omilos_grpc.CastsResponse
	(*Cast)(nil),                   // 2: omilos_grpc.Cast
	(*ViewContext)(nil),            // 3: omilos_grpc.ViewContext
	(*Author)(nil),                 // 4: omilos_grpc.Author
	(*ProfilePicture)(nil),         // 5: omilos_grpc.ProfilePicture
	(*wrapperspb.StringValue)(nil), // 6: google.protobuf.StringValue
}
var file_omilos_proto_depIdxs = []int32{
	6, // 0: omilos_grpc.CastsRequest.fid:type_name -> google.protobuf.StringValue
	2, // 1: omilos_grpc.CastsResponse.casts:type_name -> omilos_grpc.Cast
	3, // 2: omilos_grpc.Cast.view_context:type_name -> omilos_grpc.ViewContext
	5, // 3: omilos_grpc.Author.pfp:type_name -> omilos_grpc.ProfilePicture
	0, // 4: omilos_grpc.Omilos.Casts:input_type -> omilos_grpc.CastsRequest
	1, // 5: omilos_grpc.Omilos.Casts:output_type -> omilos_grpc.CastsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_omilos_proto_init() }
func file_omilos_proto_init() {
	if File_omilos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_omilos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omilos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omilos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omilos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omilos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_omilos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfilePicture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_omilos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_omilos_proto_goTypes,
		DependencyIndexes: file_omilos_proto_depIdxs,
		MessageInfos:      file_omilos_proto_msgTypes,
	}.Build()
	File_omilos_proto = out.File
	file_omilos_proto_rawDesc = nil
	file_omilos_proto_goTypes = nil
	file_omilos_proto_depIdxs = nil
}
