// @generated by protobuf-ts 2.8.2 with parameter long_type_number
// @generated from protobuf file "omilos.proto" (package "omilos_grpc", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BoolValue } from "./google/protobuf/wrappers";
import { UInt32Value } from "./google/protobuf/wrappers";
import { Timestamp } from "./google/protobuf/timestamp";
import { StringValue } from "./google/protobuf/wrappers";
import { Int64Value } from "./google/protobuf/wrappers";
/**
 * @generated from protobuf message omilos_grpc.CastIdentifier
 */
export interface CastIdentifier {
    /**
     * @generated from protobuf field: google.protobuf.Int64Value id = 1;
     */
    id?: Int64Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue hash = 2;
     */
    hash?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int64Value author_fid = 3;
     */
    authorFid?: Int64Value;
}
/**
 * @generated from protobuf message omilos_grpc.Notifications
 */
export interface Notifications {
    /**
     * @generated from protobuf field: repeated omilos_grpc.Notification notifications = 1;
     */
    notifications: Notification[];
}
/**
 * @generated from protobuf message omilos_grpc.Notification
 */
export interface Notification {
    /**
     * @generated from protobuf field: omilos_grpc.NotificationType type = 1;
     */
    type: NotificationType;
    /**
     * @generated from protobuf field: uint64 cast_id = 2;
     */
    castId: number;
    /**
     * @generated from protobuf field: string actor_display_name = 3;
     */
    actorDisplayName: string;
    /**
     * @generated from protobuf field: omilos_grpc.ProfilePicture actor_profile_picture = 4;
     */
    actorProfilePicture?: ProfilePicture;
    /**
     * @generated from protobuf field: uint32 actor_fid = 5;
     */
    actorFid: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp timestamp = 6;
     */
    timestamp?: Timestamp;
    /**
     * @generated from protobuf field: bool acknowledged = 7;
     */
    acknowledged: boolean;
}
/**
 * @generated from protobuf message omilos_grpc.UserIdentifier
 */
export interface UserIdentifier {
    /**
     * @generated from protobuf field: google.protobuf.Int64Value fid = 1;
     */
    fid?: Int64Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue username = 2;
     */
    username?: StringValue;
}
/**
 * @generated from protobuf message omilos_grpc.Publications
 */
export interface Publications {
    /**
     * @generated from protobuf field: repeated omilos_grpc.Publication publications = 1;
     */
    publications: Publication[];
}
/**
 * @generated from protobuf message omilos_grpc.Publication
 */
export interface Publication {
    /**
     * @generated from protobuf field: uint64 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string title = 2;
     */
    title: string;
    /**
     * @generated from protobuf field: string excerpt = 3;
     */
    excerpt: string;
    /**
     * @generated from protobuf field: string url = 4;
     */
    url: string;
    /**
     * @generated from protobuf field: omilos_grpc.Author author = 5;
     */
    author?: Author;
    /**
     * @generated from protobuf field: string platform = 6;
     */
    platform: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp published_at = 7;
     */
    publishedAt?: Timestamp;
}
/**
 * @generated from protobuf message omilos_grpc.Casts
 */
export interface Casts {
    /**
     * @generated from protobuf field: repeated omilos_grpc.Cast casts = 1;
     */
    casts: Cast[];
}
/**
 * @generated from protobuf message omilos_grpc.User
 */
export interface User {
    /**
     * @generated from protobuf field: uint32 fid = 1;
     */
    fid: number;
    /**
     * @generated from protobuf field: string username = 2;
     */
    username: string;
    /**
     * @generated from protobuf field: string display_name = 3;
     */
    displayName: string;
    /**
     * @generated from protobuf field: omilos_grpc.ProfilePicture profile_picture = 4;
     */
    profilePicture?: ProfilePicture;
    /**
     * @generated from protobuf field: omilos_grpc.Profile profile = 5;
     */
    profile?: Profile;
    /**
     * @generated from protobuf field: uint32 follower_count = 6;
     */
    followerCount: number;
    /**
     * @generated from protobuf field: uint32 following_count = 7;
     */
    followingCount: number;
}
/**
 * @generated from protobuf message omilos_grpc.Profile
 */
export interface Profile {
    /**
     * @generated from protobuf field: string bio = 1;
     */
    bio: string;
}
/**
 * @generated from protobuf message omilos_grpc.Cast
 */
export interface Cast {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: number;
    /**
     * @generated from protobuf field: string hash = 2;
     */
    hash: string;
    /**
     * @generated from protobuf field: string root_parent_hash = 3;
     */
    rootParentHash: string;
    /**
     * @generated from protobuf field: string root_parent_url = 4;
     */
    rootParentUrl: string;
    /**
     * @generated from protobuf field: google.protobuf.Int64Value root_parent_id = 5;
     */
    rootParentId?: Int64Value;
    /**
     * @generated from protobuf field: google.protobuf.Int64Value parent_id = 6;
     */
    parentId?: Int64Value;
    /**
     * @generated from protobuf field: int64 author_id = 7;
     */
    authorId: number;
    /**
     * @generated from protobuf field: string text = 8;
     */
    text: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp published_at = 9;
     */
    publishedAt?: Timestamp;
    /**
     * @generated from protobuf field: uint64 replies = 10;
     */
    replies: number;
    /**
     * @generated from protobuf field: uint64 reactions = 11;
     */
    reactions: number;
    /**
     * @generated from protobuf field: uint64 recasts = 12;
     */
    recasts: number; // TODO
    /**
     * @generated from protobuf field: uint64 watches = 13;
     */
    watches: number;
    /**
     * @generated from protobuf field: bool recast = 14;
     */
    recast: boolean;
    /**
     * @generated from protobuf field: omilos_grpc.ViewerContext viewer_context = 15;
     */
    viewerContext?: ViewerContext;
    /**
     * @generated from protobuf field: omilos_grpc.Author author = 16;
     */
    author?: Author;
    /**
     * @generated from protobuf field: google.protobuf.StringValue parent_author_display_name = 17;
     */
    parentAuthorDisplayName?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Int64Value parent_author_fid = 18;
     */
    parentAuthorFid?: Int64Value;
}
/**
 * @generated from protobuf message omilos_grpc.ViewerContext
 */
export interface ViewerContext {
    /**
     * @generated from protobuf field: bool viewed = 1;
     */
    viewed: boolean;
    /**
     * @generated from protobuf field: bool recast = 2;
     */
    recast: boolean;
    /**
     * @generated from protobuf field: bool watched = 3;
     */
    watched: boolean;
    /**
     * @generated from protobuf field: bool bookmarked = 4;
     */
    bookmarked: boolean;
    /**
     * @generated from protobuf field: bool liked = 5;
     */
    liked: boolean;
}
/**
 * @generated from protobuf message omilos_grpc.Author
 */
export interface Author {
    /**
     * @generated from protobuf field: int64 fid = 1;
     */
    fid: number;
    /**
     * @generated from protobuf field: string username = 2;
     */
    username: string;
    /**
     * @generated from protobuf field: string display_name = 3;
     */
    displayName: string;
    /**
     * @generated from protobuf field: omilos_grpc.ProfilePicture profile_picture = 4;
     */
    profilePicture?: ProfilePicture;
    /**
     * @generated from protobuf field: uint64 follower_count = 5;
     */
    followerCount: number;
    /**
     * @generated from protobuf field: uint64 following_count = 6;
     */
    followingCount: number;
}
/**
 * @generated from protobuf message omilos_grpc.ProfilePicture
 */
export interface ProfilePicture {
    /**
     * @generated from protobuf field: string url = 1;
     */
    url: string;
    /**
     * @generated from protobuf field: bool verified = 2;
     */
    verified: boolean;
}
/**
 * @generated from protobuf message omilos_grpc.BaseResponse
 */
export interface BaseResponse {
}
/**
 * @generated from protobuf message omilos_grpc.GetMeRequest
 */
export interface GetMeRequest {
}
/**
 * @generated from protobuf message omilos_grpc.GetCastsRequest
 */
export interface GetCastsRequest {
    /**
     * @generated from protobuf field: string stream_id = 1;
     */
    streamId: string;
    /**
     * @generated from protobuf field: bool next = 2;
     */
    next: boolean;
    /**
     * @generated from protobuf field: omilos_grpc.UserIdentifier user = 3;
     */
    user?: UserIdentifier;
    /**
     * @generated from protobuf field: omilos_grpc.CastIdentifier cast = 4;
     */
    cast?: CastIdentifier;
    /**
     * @generated from protobuf field: google.protobuf.StringValue query = 5;
     */
    query?: StringValue;
    /**
     * @generated from protobuf field: omilos_grpc.CastStreamType type = 6;
     */
    type: CastStreamType;
}
/**
 * @generated from protobuf message omilos_grpc.GetUserRequest
 */
export interface GetUserRequest {
    /**
     * @generated from protobuf field: google.protobuf.UInt32Value fid = 1;
     */
    fid?: UInt32Value;
    /**
     * @generated from protobuf field: google.protobuf.StringValue username = 2;
     */
    username?: StringValue;
}
/**
 * @generated from protobuf message omilos_grpc.GetPublicationsRequest
 */
export interface GetPublicationsRequest {
    /**
     * @generated from protobuf field: string stream_id = 1;
     */
    streamId: string;
    /**
     * @generated from protobuf field: bool next = 2;
     */
    next: boolean;
    /**
     * @generated from protobuf field: omilos_grpc.UserIdentifier user = 3;
     */
    user?: UserIdentifier;
}
/**
 * @generated from protobuf message omilos_grpc.GetNotificationsRequest
 */
export interface GetNotificationsRequest {
    /**
     * @generated from protobuf field: string stream_id = 1;
     */
    streamId: string;
    /**
     * @generated from protobuf field: bool next = 2;
     */
    next: boolean;
    /**
     * @generated from protobuf field: omilos_grpc.NotificationStreamType type = 3;
     */
    type: NotificationStreamType;
}
/**
 * @generated from protobuf message omilos_grpc.ConnectRequest
 */
export interface ConnectRequest {
    /**
     * @generated from protobuf field: uint64 timestamp = 1;
     */
    timestamp: number;
    /**
     * @generated from protobuf field: uint64 fid = 2;
     */
    fid: number;
    /**
     * @generated from protobuf field: bytes signature = 3;
     */
    signature: Uint8Array;
}
/**
 * @generated from protobuf message omilos_grpc.ConnectResponse
 */
export interface ConnectResponse {
    /**
     * @generated from protobuf field: google.protobuf.StringValue token = 1;
     */
    token?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp expires_at = 2;
     */
    expiresAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.StringValue public_key = 3;
     */
    publicKey?: StringValue;
    /**
     * @generated from protobuf field: google.protobuf.StringValue metadata = 4;
     */
    metadata?: StringValue;
}
/**
 * @generated from protobuf message omilos_grpc.PostCastRequest
 */
export interface PostCastRequest {
    /**
     * @generated from protobuf field: string text = 1;
     */
    text: string;
    /**
     * @generated from protobuf field: google.protobuf.Int64Value parent_id = 2;
     */
    parentId?: Int64Value;
}
/**
 * @generated from protobuf message omilos_grpc.UserCastContextUpdate
 */
export interface UserCastContextUpdate {
    /**
     * @generated from protobuf field: omilos_grpc.CastIdentifier cast = 1;
     */
    cast?: CastIdentifier;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue viewed = 2;
     */
    viewed?: BoolValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue watched = 3;
     */
    watched?: BoolValue;
    /**
     * @generated from protobuf field: google.protobuf.BoolValue bookmarked = 4;
     */
    bookmarked?: BoolValue;
}
/**
 * @generated from protobuf message omilos_grpc.LikeCastResponse
 */
export interface LikeCastResponse {
}
/**
 * @generated from protobuf message omilos_grpc.SearchCastRequest
 */
export interface SearchCastRequest {
    /**
     * @generated from protobuf field: string query = 1;
     */
    query: string;
}
/**
 * @generated from protobuf enum omilos_grpc.ReactionType
 */
export enum ReactionType {
    /**
     * @generated from protobuf enum value: UNSPECIFIED_REACTION_TYPE = 0;
     */
    UNSPECIFIED_REACTION_TYPE = 0,
    /**
     * @generated from protobuf enum value: LIKE = 1;
     */
    LIKE = 1,
    /**
     * @generated from protobuf enum value: RECAST = 2;
     */
    RECAST = 2
}
/**
 * @generated from protobuf enum omilos_grpc.NotificationType
 */
export enum NotificationType {
    /**
     * @generated from protobuf enum value: UNSPECIFIED_NOTIFICATION_TYPE = 0;
     */
    UNSPECIFIED_NOTIFICATION_TYPE = 0,
    /**
     * @generated from protobuf enum value: CAST_MENTION = 1;
     */
    CAST_MENTION = 1,
    /**
     * @generated from protobuf enum value: CAST_LIKE = 2;
     */
    CAST_LIKE = 2,
    /**
     * @generated from protobuf enum value: CAST_REPLY = 3;
     */
    CAST_REPLY = 3
}
/**
 * @generated from protobuf enum omilos_grpc.CastStreamType
 */
export enum CastStreamType {
    /**
     * @generated from protobuf enum value: UNSPECIFIED_CAST_STREAM_TYPE = 0;
     */
    UNSPECIFIED_CAST_STREAM_TYPE = 0,
    /**
     * @generated from protobuf enum value: CHILDREN = 1;
     */
    CHILDREN = 1,
    /**
     * @generated from protobuf enum value: THREAD_CASTS = 2;
     */
    THREAD_CASTS = 2,
    /**
     * @generated from protobuf enum value: USER_THREADS = 3;
     */
    USER_THREADS = 3,
    /**
     * @generated from protobuf enum value: USER_LIKES = 4;
     */
    USER_LIKES = 4,
    /**
     * @generated from protobuf enum value: USER_REPLIES = 5;
     */
    USER_REPLIES = 5,
    /**
     * @generated from protobuf enum value: LATEST = 6;
     */
    LATEST = 6,
    /**
     * @generated from protobuf enum value: TRENDING = 7;
     */
    TRENDING = 7,
    /**
     * @generated from protobuf enum value: HIGHLIGHTS = 8;
     */
    HIGHLIGHTS = 8,
    /**
     * @generated from protobuf enum value: RECOMMENDED = 9;
     */
    RECOMMENDED = 9,
    /**
     * @generated from protobuf enum value: BOOKMARKED = 10;
     */
    BOOKMARKED = 10,
    /**
     * @generated from protobuf enum value: SEARCH = 11;
     */
    SEARCH = 11
}
/**
 * @generated from protobuf enum omilos_grpc.NotificationStreamType
 */
export enum NotificationStreamType {
    /**
     * @generated from protobuf enum value: UNSPECIFIED_NOTIFICATION_STREAM_TYPE = 0;
     */
    UNSPECIFIED_NOTIFICATION_STREAM_TYPE = 0,
    /**
     * @generated from protobuf enum value: ALL = 1;
     */
    ALL = 1,
    /**
     * @generated from protobuf enum value: CONVERSATIONS = 2;
     */
    CONVERSATIONS = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class CastIdentifier$Type extends MessageType<CastIdentifier> {
    constructor() {
        super("omilos_grpc.CastIdentifier", [
            { no: 1, name: "id", kind: "message", T: () => Int64Value },
            { no: 2, name: "hash", kind: "message", T: () => StringValue },
            { no: 3, name: "author_fid", kind: "message", T: () => Int64Value }
        ]);
    }
    create(value?: PartialMessage<CastIdentifier>): CastIdentifier {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<CastIdentifier>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CastIdentifier): CastIdentifier {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int64Value id */ 1:
                    message.id = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.id);
                    break;
                case /* google.protobuf.StringValue hash */ 2:
                    message.hash = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.hash);
                    break;
                case /* google.protobuf.Int64Value author_fid */ 3:
                    message.authorFid = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.authorFid);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CastIdentifier, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int64Value id = 1; */
        if (message.id)
            Int64Value.internalBinaryWrite(message.id, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue hash = 2; */
        if (message.hash)
            StringValue.internalBinaryWrite(message.hash, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int64Value author_fid = 3; */
        if (message.authorFid)
            Int64Value.internalBinaryWrite(message.authorFid, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.CastIdentifier
 */
export const CastIdentifier = new CastIdentifier$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Notifications$Type extends MessageType<Notifications> {
    constructor() {
        super("omilos_grpc.Notifications", [
            { no: 1, name: "notifications", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Notification }
        ]);
    }
    create(value?: PartialMessage<Notifications>): Notifications {
        const message = { notifications: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Notifications>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Notifications): Notifications {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated omilos_grpc.Notification notifications */ 1:
                    message.notifications.push(Notification.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Notifications, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated omilos_grpc.Notification notifications = 1; */
        for (let i = 0; i < message.notifications.length; i++)
            Notification.internalBinaryWrite(message.notifications[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Notifications
 */
export const Notifications = new Notifications$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Notification$Type extends MessageType<Notification> {
    constructor() {
        super("omilos_grpc.Notification", [
            { no: 1, name: "type", kind: "enum", T: () => ["omilos_grpc.NotificationType", NotificationType] },
            { no: 2, name: "cast_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 3, name: "actor_display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "actor_profile_picture", kind: "message", T: () => ProfilePicture },
            { no: 5, name: "actor_fid", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "timestamp", kind: "message", T: () => Timestamp },
            { no: 7, name: "acknowledged", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Notification>): Notification {
        const message = { type: 0, castId: 0, actorDisplayName: "", actorFid: 0, acknowledged: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Notification>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Notification): Notification {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* omilos_grpc.NotificationType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* uint64 cast_id */ 2:
                    message.castId = reader.uint64().toNumber();
                    break;
                case /* string actor_display_name */ 3:
                    message.actorDisplayName = reader.string();
                    break;
                case /* omilos_grpc.ProfilePicture actor_profile_picture */ 4:
                    message.actorProfilePicture = ProfilePicture.internalBinaryRead(reader, reader.uint32(), options, message.actorProfilePicture);
                    break;
                case /* uint32 actor_fid */ 5:
                    message.actorFid = reader.uint32();
                    break;
                case /* google.protobuf.Timestamp timestamp */ 6:
                    message.timestamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.timestamp);
                    break;
                case /* bool acknowledged */ 7:
                    message.acknowledged = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Notification, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* omilos_grpc.NotificationType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* uint64 cast_id = 2; */
        if (message.castId !== 0)
            writer.tag(2, WireType.Varint).uint64(message.castId);
        /* string actor_display_name = 3; */
        if (message.actorDisplayName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.actorDisplayName);
        /* omilos_grpc.ProfilePicture actor_profile_picture = 4; */
        if (message.actorProfilePicture)
            ProfilePicture.internalBinaryWrite(message.actorProfilePicture, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* uint32 actor_fid = 5; */
        if (message.actorFid !== 0)
            writer.tag(5, WireType.Varint).uint32(message.actorFid);
        /* google.protobuf.Timestamp timestamp = 6; */
        if (message.timestamp)
            Timestamp.internalBinaryWrite(message.timestamp, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* bool acknowledged = 7; */
        if (message.acknowledged !== false)
            writer.tag(7, WireType.Varint).bool(message.acknowledged);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Notification
 */
export const Notification = new Notification$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserIdentifier$Type extends MessageType<UserIdentifier> {
    constructor() {
        super("omilos_grpc.UserIdentifier", [
            { no: 1, name: "fid", kind: "message", T: () => Int64Value },
            { no: 2, name: "username", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<UserIdentifier>): UserIdentifier {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<UserIdentifier>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserIdentifier): UserIdentifier {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Int64Value fid */ 1:
                    message.fid = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.fid);
                    break;
                case /* google.protobuf.StringValue username */ 2:
                    message.username = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.username);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserIdentifier, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Int64Value fid = 1; */
        if (message.fid)
            Int64Value.internalBinaryWrite(message.fid, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue username = 2; */
        if (message.username)
            StringValue.internalBinaryWrite(message.username, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.UserIdentifier
 */
export const UserIdentifier = new UserIdentifier$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Publications$Type extends MessageType<Publications> {
    constructor() {
        super("omilos_grpc.Publications", [
            { no: 1, name: "publications", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Publication }
        ]);
    }
    create(value?: PartialMessage<Publications>): Publications {
        const message = { publications: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Publications>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Publications): Publications {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated omilos_grpc.Publication publications */ 1:
                    message.publications.push(Publication.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Publications, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated omilos_grpc.Publication publications = 1; */
        for (let i = 0; i < message.publications.length; i++)
            Publication.internalBinaryWrite(message.publications[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Publications
 */
export const Publications = new Publications$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Publication$Type extends MessageType<Publication> {
    constructor() {
        super("omilos_grpc.Publication", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "excerpt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "author", kind: "message", T: () => Author },
            { no: 6, name: "platform", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "published_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Publication>): Publication {
        const message = { id: 0, title: "", excerpt: "", url: "", platform: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Publication>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Publication): Publication {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toNumber();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string excerpt */ 3:
                    message.excerpt = reader.string();
                    break;
                case /* string url */ 4:
                    message.url = reader.string();
                    break;
                case /* omilos_grpc.Author author */ 5:
                    message.author = Author.internalBinaryRead(reader, reader.uint32(), options, message.author);
                    break;
                case /* string platform */ 6:
                    message.platform = reader.string();
                    break;
                case /* google.protobuf.Timestamp published_at */ 7:
                    message.publishedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publishedAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Publication, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string excerpt = 3; */
        if (message.excerpt !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.excerpt);
        /* string url = 4; */
        if (message.url !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.url);
        /* omilos_grpc.Author author = 5; */
        if (message.author)
            Author.internalBinaryWrite(message.author, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* string platform = 6; */
        if (message.platform !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.platform);
        /* google.protobuf.Timestamp published_at = 7; */
        if (message.publishedAt)
            Timestamp.internalBinaryWrite(message.publishedAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Publication
 */
export const Publication = new Publication$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Casts$Type extends MessageType<Casts> {
    constructor() {
        super("omilos_grpc.Casts", [
            { no: 1, name: "casts", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Cast }
        ]);
    }
    create(value?: PartialMessage<Casts>): Casts {
        const message = { casts: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Casts>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Casts): Casts {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated omilos_grpc.Cast casts */ 1:
                    message.casts.push(Cast.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Casts, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated omilos_grpc.Cast casts = 1; */
        for (let i = 0; i < message.casts.length; i++)
            Cast.internalBinaryWrite(message.casts[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Casts
 */
export const Casts = new Casts$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User$Type extends MessageType<User> {
    constructor() {
        super("omilos_grpc.User", [
            { no: 1, name: "fid", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "profile_picture", kind: "message", T: () => ProfilePicture },
            { no: 5, name: "profile", kind: "message", T: () => Profile },
            { no: 6, name: "follower_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "following_count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<User>): User {
        const message = { fid: 0, username: "", displayName: "", followerCount: 0, followingCount: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<User>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User): User {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 fid */ 1:
                    message.fid = reader.uint32();
                    break;
                case /* string username */ 2:
                    message.username = reader.string();
                    break;
                case /* string display_name */ 3:
                    message.displayName = reader.string();
                    break;
                case /* omilos_grpc.ProfilePicture profile_picture */ 4:
                    message.profilePicture = ProfilePicture.internalBinaryRead(reader, reader.uint32(), options, message.profilePicture);
                    break;
                case /* omilos_grpc.Profile profile */ 5:
                    message.profile = Profile.internalBinaryRead(reader, reader.uint32(), options, message.profile);
                    break;
                case /* uint32 follower_count */ 6:
                    message.followerCount = reader.uint32();
                    break;
                case /* uint32 following_count */ 7:
                    message.followingCount = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 fid = 1; */
        if (message.fid !== 0)
            writer.tag(1, WireType.Varint).uint32(message.fid);
        /* string username = 2; */
        if (message.username !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.username);
        /* string display_name = 3; */
        if (message.displayName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.displayName);
        /* omilos_grpc.ProfilePicture profile_picture = 4; */
        if (message.profilePicture)
            ProfilePicture.internalBinaryWrite(message.profilePicture, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* omilos_grpc.Profile profile = 5; */
        if (message.profile)
            Profile.internalBinaryWrite(message.profile, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* uint32 follower_count = 6; */
        if (message.followerCount !== 0)
            writer.tag(6, WireType.Varint).uint32(message.followerCount);
        /* uint32 following_count = 7; */
        if (message.followingCount !== 0)
            writer.tag(7, WireType.Varint).uint32(message.followingCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.User
 */
export const User = new User$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Profile$Type extends MessageType<Profile> {
    constructor() {
        super("omilos_grpc.Profile", [
            { no: 1, name: "bio", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Profile>): Profile {
        const message = { bio: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Profile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Profile): Profile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string bio */ 1:
                    message.bio = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Profile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string bio = 1; */
        if (message.bio !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.bio);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Profile
 */
export const Profile = new Profile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Cast$Type extends MessageType<Cast> {
    constructor() {
        super("omilos_grpc.Cast", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "root_parent_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "root_parent_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "root_parent_id", kind: "message", T: () => Int64Value },
            { no: 6, name: "parent_id", kind: "message", T: () => Int64Value },
            { no: 7, name: "author_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 8, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "published_at", kind: "message", T: () => Timestamp },
            { no: 10, name: "replies", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 11, name: "reactions", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 12, name: "recasts", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 13, name: "watches", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 14, name: "recast", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 15, name: "viewer_context", kind: "message", T: () => ViewerContext },
            { no: 16, name: "author", kind: "message", T: () => Author },
            { no: 17, name: "parent_author_display_name", kind: "message", T: () => StringValue },
            { no: 18, name: "parent_author_fid", kind: "message", T: () => Int64Value }
        ]);
    }
    create(value?: PartialMessage<Cast>): Cast {
        const message = { id: 0, hash: "", rootParentHash: "", rootParentUrl: "", authorId: 0, text: "", replies: 0, reactions: 0, recasts: 0, watches: 0, recast: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Cast>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Cast): Cast {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 id */ 1:
                    message.id = reader.int64().toNumber();
                    break;
                case /* string hash */ 2:
                    message.hash = reader.string();
                    break;
                case /* string root_parent_hash */ 3:
                    message.rootParentHash = reader.string();
                    break;
                case /* string root_parent_url */ 4:
                    message.rootParentUrl = reader.string();
                    break;
                case /* google.protobuf.Int64Value root_parent_id */ 5:
                    message.rootParentId = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.rootParentId);
                    break;
                case /* google.protobuf.Int64Value parent_id */ 6:
                    message.parentId = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.parentId);
                    break;
                case /* int64 author_id */ 7:
                    message.authorId = reader.int64().toNumber();
                    break;
                case /* string text */ 8:
                    message.text = reader.string();
                    break;
                case /* google.protobuf.Timestamp published_at */ 9:
                    message.publishedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.publishedAt);
                    break;
                case /* uint64 replies */ 10:
                    message.replies = reader.uint64().toNumber();
                    break;
                case /* uint64 reactions */ 11:
                    message.reactions = reader.uint64().toNumber();
                    break;
                case /* uint64 recasts */ 12:
                    message.recasts = reader.uint64().toNumber();
                    break;
                case /* uint64 watches */ 13:
                    message.watches = reader.uint64().toNumber();
                    break;
                case /* bool recast */ 14:
                    message.recast = reader.bool();
                    break;
                case /* omilos_grpc.ViewerContext viewer_context */ 15:
                    message.viewerContext = ViewerContext.internalBinaryRead(reader, reader.uint32(), options, message.viewerContext);
                    break;
                case /* omilos_grpc.Author author */ 16:
                    message.author = Author.internalBinaryRead(reader, reader.uint32(), options, message.author);
                    break;
                case /* google.protobuf.StringValue parent_author_display_name */ 17:
                    message.parentAuthorDisplayName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.parentAuthorDisplayName);
                    break;
                case /* google.protobuf.Int64Value parent_author_fid */ 18:
                    message.parentAuthorFid = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.parentAuthorFid);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Cast, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int64(message.id);
        /* string hash = 2; */
        if (message.hash !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.hash);
        /* string root_parent_hash = 3; */
        if (message.rootParentHash !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.rootParentHash);
        /* string root_parent_url = 4; */
        if (message.rootParentUrl !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.rootParentUrl);
        /* google.protobuf.Int64Value root_parent_id = 5; */
        if (message.rootParentId)
            Int64Value.internalBinaryWrite(message.rootParentId, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int64Value parent_id = 6; */
        if (message.parentId)
            Int64Value.internalBinaryWrite(message.parentId, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* int64 author_id = 7; */
        if (message.authorId !== 0)
            writer.tag(7, WireType.Varint).int64(message.authorId);
        /* string text = 8; */
        if (message.text !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.text);
        /* google.protobuf.Timestamp published_at = 9; */
        if (message.publishedAt)
            Timestamp.internalBinaryWrite(message.publishedAt, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* uint64 replies = 10; */
        if (message.replies !== 0)
            writer.tag(10, WireType.Varint).uint64(message.replies);
        /* uint64 reactions = 11; */
        if (message.reactions !== 0)
            writer.tag(11, WireType.Varint).uint64(message.reactions);
        /* uint64 recasts = 12; */
        if (message.recasts !== 0)
            writer.tag(12, WireType.Varint).uint64(message.recasts);
        /* uint64 watches = 13; */
        if (message.watches !== 0)
            writer.tag(13, WireType.Varint).uint64(message.watches);
        /* bool recast = 14; */
        if (message.recast !== false)
            writer.tag(14, WireType.Varint).bool(message.recast);
        /* omilos_grpc.ViewerContext viewer_context = 15; */
        if (message.viewerContext)
            ViewerContext.internalBinaryWrite(message.viewerContext, writer.tag(15, WireType.LengthDelimited).fork(), options).join();
        /* omilos_grpc.Author author = 16; */
        if (message.author)
            Author.internalBinaryWrite(message.author, writer.tag(16, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue parent_author_display_name = 17; */
        if (message.parentAuthorDisplayName)
            StringValue.internalBinaryWrite(message.parentAuthorDisplayName, writer.tag(17, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Int64Value parent_author_fid = 18; */
        if (message.parentAuthorFid)
            Int64Value.internalBinaryWrite(message.parentAuthorFid, writer.tag(18, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Cast
 */
export const Cast = new Cast$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ViewerContext$Type extends MessageType<ViewerContext> {
    constructor() {
        super("omilos_grpc.ViewerContext", [
            { no: 1, name: "viewed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "recast", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "watched", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "bookmarked", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "liked", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ViewerContext>): ViewerContext {
        const message = { viewed: false, recast: false, watched: false, bookmarked: false, liked: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ViewerContext>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewerContext): ViewerContext {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool viewed */ 1:
                    message.viewed = reader.bool();
                    break;
                case /* bool recast */ 2:
                    message.recast = reader.bool();
                    break;
                case /* bool watched */ 3:
                    message.watched = reader.bool();
                    break;
                case /* bool bookmarked */ 4:
                    message.bookmarked = reader.bool();
                    break;
                case /* bool liked */ 5:
                    message.liked = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ViewerContext, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool viewed = 1; */
        if (message.viewed !== false)
            writer.tag(1, WireType.Varint).bool(message.viewed);
        /* bool recast = 2; */
        if (message.recast !== false)
            writer.tag(2, WireType.Varint).bool(message.recast);
        /* bool watched = 3; */
        if (message.watched !== false)
            writer.tag(3, WireType.Varint).bool(message.watched);
        /* bool bookmarked = 4; */
        if (message.bookmarked !== false)
            writer.tag(4, WireType.Varint).bool(message.bookmarked);
        /* bool liked = 5; */
        if (message.liked !== false)
            writer.tag(5, WireType.Varint).bool(message.liked);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.ViewerContext
 */
export const ViewerContext = new ViewerContext$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Author$Type extends MessageType<Author> {
    constructor() {
        super("omilos_grpc.Author", [
            { no: 1, name: "fid", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "profile_picture", kind: "message", T: () => ProfilePicture },
            { no: 5, name: "follower_count", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 6, name: "following_count", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ }
        ]);
    }
    create(value?: PartialMessage<Author>): Author {
        const message = { fid: 0, username: "", displayName: "", followerCount: 0, followingCount: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Author>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Author): Author {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 fid */ 1:
                    message.fid = reader.int64().toNumber();
                    break;
                case /* string username */ 2:
                    message.username = reader.string();
                    break;
                case /* string display_name */ 3:
                    message.displayName = reader.string();
                    break;
                case /* omilos_grpc.ProfilePicture profile_picture */ 4:
                    message.profilePicture = ProfilePicture.internalBinaryRead(reader, reader.uint32(), options, message.profilePicture);
                    break;
                case /* uint64 follower_count */ 5:
                    message.followerCount = reader.uint64().toNumber();
                    break;
                case /* uint64 following_count */ 6:
                    message.followingCount = reader.uint64().toNumber();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Author, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 fid = 1; */
        if (message.fid !== 0)
            writer.tag(1, WireType.Varint).int64(message.fid);
        /* string username = 2; */
        if (message.username !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.username);
        /* string display_name = 3; */
        if (message.displayName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.displayName);
        /* omilos_grpc.ProfilePicture profile_picture = 4; */
        if (message.profilePicture)
            ProfilePicture.internalBinaryWrite(message.profilePicture, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* uint64 follower_count = 5; */
        if (message.followerCount !== 0)
            writer.tag(5, WireType.Varint).uint64(message.followerCount);
        /* uint64 following_count = 6; */
        if (message.followingCount !== 0)
            writer.tag(6, WireType.Varint).uint64(message.followingCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.Author
 */
export const Author = new Author$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProfilePicture$Type extends MessageType<ProfilePicture> {
    constructor() {
        super("omilos_grpc.ProfilePicture", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "verified", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ProfilePicture>): ProfilePicture {
        const message = { url: "", verified: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ProfilePicture>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProfilePicture): ProfilePicture {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string url */ 1:
                    message.url = reader.string();
                    break;
                case /* bool verified */ 2:
                    message.verified = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProfilePicture, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string url = 1; */
        if (message.url !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.url);
        /* bool verified = 2; */
        if (message.verified !== false)
            writer.tag(2, WireType.Varint).bool(message.verified);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.ProfilePicture
 */
export const ProfilePicture = new ProfilePicture$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BaseResponse$Type extends MessageType<BaseResponse> {
    constructor() {
        super("omilos_grpc.BaseResponse", []);
    }
    create(value?: PartialMessage<BaseResponse>): BaseResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<BaseResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BaseResponse): BaseResponse {
        return target ?? this.create();
    }
    internalBinaryWrite(message: BaseResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.BaseResponse
 */
export const BaseResponse = new BaseResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMeRequest$Type extends MessageType<GetMeRequest> {
    constructor() {
        super("omilos_grpc.GetMeRequest", []);
    }
    create(value?: PartialMessage<GetMeRequest>): GetMeRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetMeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMeRequest): GetMeRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: GetMeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.GetMeRequest
 */
export const GetMeRequest = new GetMeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCastsRequest$Type extends MessageType<GetCastsRequest> {
    constructor() {
        super("omilos_grpc.GetCastsRequest", [
            { no: 1, name: "stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "next", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "user", kind: "message", T: () => UserIdentifier },
            { no: 4, name: "cast", kind: "message", T: () => CastIdentifier },
            { no: 5, name: "query", kind: "message", T: () => StringValue },
            { no: 6, name: "type", kind: "enum", T: () => ["omilos_grpc.CastStreamType", CastStreamType] }
        ]);
    }
    create(value?: PartialMessage<GetCastsRequest>): GetCastsRequest {
        const message = { streamId: "", next: false, type: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetCastsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCastsRequest): GetCastsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string stream_id */ 1:
                    message.streamId = reader.string();
                    break;
                case /* bool next */ 2:
                    message.next = reader.bool();
                    break;
                case /* omilos_grpc.UserIdentifier user */ 3:
                    message.user = UserIdentifier.internalBinaryRead(reader, reader.uint32(), options, message.user);
                    break;
                case /* omilos_grpc.CastIdentifier cast */ 4:
                    message.cast = CastIdentifier.internalBinaryRead(reader, reader.uint32(), options, message.cast);
                    break;
                case /* google.protobuf.StringValue query */ 5:
                    message.query = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.query);
                    break;
                case /* omilos_grpc.CastStreamType type */ 6:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCastsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string stream_id = 1; */
        if (message.streamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streamId);
        /* bool next = 2; */
        if (message.next !== false)
            writer.tag(2, WireType.Varint).bool(message.next);
        /* omilos_grpc.UserIdentifier user = 3; */
        if (message.user)
            UserIdentifier.internalBinaryWrite(message.user, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* omilos_grpc.CastIdentifier cast = 4; */
        if (message.cast)
            CastIdentifier.internalBinaryWrite(message.cast, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue query = 5; */
        if (message.query)
            StringValue.internalBinaryWrite(message.query, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* omilos_grpc.CastStreamType type = 6; */
        if (message.type !== 0)
            writer.tag(6, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.GetCastsRequest
 */
export const GetCastsRequest = new GetCastsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserRequest$Type extends MessageType<GetUserRequest> {
    constructor() {
        super("omilos_grpc.GetUserRequest", [
            { no: 1, name: "fid", kind: "message", T: () => UInt32Value },
            { no: 2, name: "username", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<GetUserRequest>): GetUserRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetUserRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetUserRequest): GetUserRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.UInt32Value fid */ 1:
                    message.fid = UInt32Value.internalBinaryRead(reader, reader.uint32(), options, message.fid);
                    break;
                case /* google.protobuf.StringValue username */ 2:
                    message.username = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.username);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetUserRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.UInt32Value fid = 1; */
        if (message.fid)
            UInt32Value.internalBinaryWrite(message.fid, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue username = 2; */
        if (message.username)
            StringValue.internalBinaryWrite(message.username, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.GetUserRequest
 */
export const GetUserRequest = new GetUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPublicationsRequest$Type extends MessageType<GetPublicationsRequest> {
    constructor() {
        super("omilos_grpc.GetPublicationsRequest", [
            { no: 1, name: "stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "next", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "user", kind: "message", T: () => UserIdentifier }
        ]);
    }
    create(value?: PartialMessage<GetPublicationsRequest>): GetPublicationsRequest {
        const message = { streamId: "", next: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetPublicationsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPublicationsRequest): GetPublicationsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string stream_id */ 1:
                    message.streamId = reader.string();
                    break;
                case /* bool next */ 2:
                    message.next = reader.bool();
                    break;
                case /* omilos_grpc.UserIdentifier user */ 3:
                    message.user = UserIdentifier.internalBinaryRead(reader, reader.uint32(), options, message.user);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPublicationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string stream_id = 1; */
        if (message.streamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streamId);
        /* bool next = 2; */
        if (message.next !== false)
            writer.tag(2, WireType.Varint).bool(message.next);
        /* omilos_grpc.UserIdentifier user = 3; */
        if (message.user)
            UserIdentifier.internalBinaryWrite(message.user, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.GetPublicationsRequest
 */
export const GetPublicationsRequest = new GetPublicationsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetNotificationsRequest$Type extends MessageType<GetNotificationsRequest> {
    constructor() {
        super("omilos_grpc.GetNotificationsRequest", [
            { no: 1, name: "stream_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "next", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["omilos_grpc.NotificationStreamType", NotificationStreamType] }
        ]);
    }
    create(value?: PartialMessage<GetNotificationsRequest>): GetNotificationsRequest {
        const message = { streamId: "", next: false, type: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<GetNotificationsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetNotificationsRequest): GetNotificationsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string stream_id */ 1:
                    message.streamId = reader.string();
                    break;
                case /* bool next */ 2:
                    message.next = reader.bool();
                    break;
                case /* omilos_grpc.NotificationStreamType type */ 3:
                    message.type = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetNotificationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string stream_id = 1; */
        if (message.streamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.streamId);
        /* bool next = 2; */
        if (message.next !== false)
            writer.tag(2, WireType.Varint).bool(message.next);
        /* omilos_grpc.NotificationStreamType type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.GetNotificationsRequest
 */
export const GetNotificationsRequest = new GetNotificationsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectRequest$Type extends MessageType<ConnectRequest> {
    constructor() {
        super("omilos_grpc.ConnectRequest", [
            { no: 1, name: "timestamp", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "fid", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 3, name: "signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<ConnectRequest>): ConnectRequest {
        const message = { timestamp: 0, fid: 0, signature: new Uint8Array(0) };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ConnectRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectRequest): ConnectRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 timestamp */ 1:
                    message.timestamp = reader.uint64().toNumber();
                    break;
                case /* uint64 fid */ 2:
                    message.fid = reader.uint64().toNumber();
                    break;
                case /* bytes signature */ 3:
                    message.signature = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 timestamp = 1; */
        if (message.timestamp !== 0)
            writer.tag(1, WireType.Varint).uint64(message.timestamp);
        /* uint64 fid = 2; */
        if (message.fid !== 0)
            writer.tag(2, WireType.Varint).uint64(message.fid);
        /* bytes signature = 3; */
        if (message.signature.length)
            writer.tag(3, WireType.LengthDelimited).bytes(message.signature);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.ConnectRequest
 */
export const ConnectRequest = new ConnectRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConnectResponse$Type extends MessageType<ConnectResponse> {
    constructor() {
        super("omilos_grpc.ConnectResponse", [
            { no: 1, name: "token", kind: "message", T: () => StringValue },
            { no: 2, name: "expires_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "public_key", kind: "message", T: () => StringValue },
            { no: 4, name: "metadata", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<ConnectResponse>): ConnectResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<ConnectResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ConnectResponse): ConnectResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.StringValue token */ 1:
                    message.token = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.token);
                    break;
                case /* google.protobuf.Timestamp expires_at */ 2:
                    message.expiresAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.expiresAt);
                    break;
                case /* google.protobuf.StringValue public_key */ 3:
                    message.publicKey = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.publicKey);
                    break;
                case /* google.protobuf.StringValue metadata */ 4:
                    message.metadata = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.metadata);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ConnectResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.StringValue token = 1; */
        if (message.token)
            StringValue.internalBinaryWrite(message.token, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp expires_at = 2; */
        if (message.expiresAt)
            Timestamp.internalBinaryWrite(message.expiresAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue public_key = 3; */
        if (message.publicKey)
            StringValue.internalBinaryWrite(message.publicKey, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.StringValue metadata = 4; */
        if (message.metadata)
            StringValue.internalBinaryWrite(message.metadata, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.ConnectResponse
 */
export const ConnectResponse = new ConnectResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostCastRequest$Type extends MessageType<PostCastRequest> {
    constructor() {
        super("omilos_grpc.PostCastRequest", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "parent_id", kind: "message", T: () => Int64Value }
        ]);
    }
    create(value?: PartialMessage<PostCastRequest>): PostCastRequest {
        const message = { text: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PostCastRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostCastRequest): PostCastRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                case /* google.protobuf.Int64Value parent_id */ 2:
                    message.parentId = Int64Value.internalBinaryRead(reader, reader.uint32(), options, message.parentId);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostCastRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        /* google.protobuf.Int64Value parent_id = 2; */
        if (message.parentId)
            Int64Value.internalBinaryWrite(message.parentId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.PostCastRequest
 */
export const PostCastRequest = new PostCastRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserCastContextUpdate$Type extends MessageType<UserCastContextUpdate> {
    constructor() {
        super("omilos_grpc.UserCastContextUpdate", [
            { no: 1, name: "cast", kind: "message", T: () => CastIdentifier },
            { no: 2, name: "viewed", kind: "message", T: () => BoolValue },
            { no: 3, name: "watched", kind: "message", T: () => BoolValue },
            { no: 4, name: "bookmarked", kind: "message", T: () => BoolValue }
        ]);
    }
    create(value?: PartialMessage<UserCastContextUpdate>): UserCastContextUpdate {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<UserCastContextUpdate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserCastContextUpdate): UserCastContextUpdate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* omilos_grpc.CastIdentifier cast */ 1:
                    message.cast = CastIdentifier.internalBinaryRead(reader, reader.uint32(), options, message.cast);
                    break;
                case /* google.protobuf.BoolValue viewed */ 2:
                    message.viewed = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.viewed);
                    break;
                case /* google.protobuf.BoolValue watched */ 3:
                    message.watched = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.watched);
                    break;
                case /* google.protobuf.BoolValue bookmarked */ 4:
                    message.bookmarked = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.bookmarked);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserCastContextUpdate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* omilos_grpc.CastIdentifier cast = 1; */
        if (message.cast)
            CastIdentifier.internalBinaryWrite(message.cast, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue viewed = 2; */
        if (message.viewed)
            BoolValue.internalBinaryWrite(message.viewed, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue watched = 3; */
        if (message.watched)
            BoolValue.internalBinaryWrite(message.watched, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.BoolValue bookmarked = 4; */
        if (message.bookmarked)
            BoolValue.internalBinaryWrite(message.bookmarked, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.UserCastContextUpdate
 */
export const UserCastContextUpdate = new UserCastContextUpdate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LikeCastResponse$Type extends MessageType<LikeCastResponse> {
    constructor() {
        super("omilos_grpc.LikeCastResponse", []);
    }
    create(value?: PartialMessage<LikeCastResponse>): LikeCastResponse {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<LikeCastResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LikeCastResponse): LikeCastResponse {
        return target ?? this.create();
    }
    internalBinaryWrite(message: LikeCastResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.LikeCastResponse
 */
export const LikeCastResponse = new LikeCastResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SearchCastRequest$Type extends MessageType<SearchCastRequest> {
    constructor() {
        super("omilos_grpc.SearchCastRequest", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SearchCastRequest>): SearchCastRequest {
        const message = { query: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SearchCastRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchCastRequest): SearchCastRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query */ 1:
                    message.query = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SearchCastRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query = 1; */
        if (message.query !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.query);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message omilos_grpc.SearchCastRequest
 */
export const SearchCastRequest = new SearchCastRequest$Type();
/**
 * @generated ServiceType for protobuf service omilos_grpc.Omilos
 */
export const Omilos = new ServiceType("omilos_grpc.Omilos", [
    { name: "Connect", options: {}, I: ConnectRequest, O: ConnectResponse },
    { name: "PostCast", options: {}, I: PostCastRequest, O: Cast },
    { name: "LikeCast", options: {}, I: CastIdentifier, O: BaseResponse },
    { name: "RecastCast", options: {}, I: CastIdentifier, O: BaseResponse },
    { name: "UpdateUserCastContext", options: {}, I: UserCastContextUpdate, O: BaseResponse },
    { name: "GetMe", options: {}, I: GetMeRequest, O: User },
    { name: "GetNotifications", options: {}, I: GetNotificationsRequest, O: Notifications },
    { name: "GetUser", options: {}, I: GetUserRequest, O: User },
    { name: "GetCast", options: {}, I: CastIdentifier, O: Cast },
    { name: "GetCasts", options: {}, I: GetCastsRequest, O: Casts },
    { name: "GetPublications", options: {}, I: GetPublicationsRequest, O: Publications }
]);
